eureka:
  client:
    serviceUrl: #注册中心的注册地址
      defaultZone: http://127.0.0.1:8080/eureka/
server:
  port: 8082  #服务端口号--该端口不要冲突
spring:
  application:
    name: lyc-provider2 #服务名称--调用的时候根据名称来调用该服务的方法--名字绝对不能改，改了就访问不到了
  cloud:
    loadbalancer:
      ribbon:
        enabled: false