server:
  port: 10001
  servlet:
    context-path: /lyc-web3
  ssl:
#    key-store: classpath:springboot_keystore.jks
#    key-store-password: mypassword
#    key-store-type: JKS
#    key-alias: springboot
    key-store: classpath:root.jks
    key-store-password: 123456
    key-store-type: JKS
    key-alias: root