server:
  port: 8080

eureka:
  server:
    enable-self-preservation: false  # 关闭自我保护
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #注册中心地址
    registerWithEureka: false  # 单机模式 设置为false
    fetchRegistry: false       # 单机模式 设置为false
  instance:
    hostname: 127.0.0.1    # 指定该Eureka实例的主机名
    prefer-ip-address: true